export const CONFIG = {
  gridColumns: 13,
  gridRows: 13,
  tileSize: 32,
  sidePanelWidth: 96,
  tankSize: 26,
  bulletSize: 6,
  fixedStepMs: 16,
  turnSnapPixels: 16,
  maxActiveEnemies: 4,
  enemiesPerLevel: 20,
  playerLives: 3,
  playerFireCooldownMs: 380,
  enemySpawnIntervalMs: 1500,
  enemySpawnLockMs: 850,
  playerSpeed: 80,
  iceSlideMs: 280,
  iceSlideSpeedScale: 0.82,
  steelHitsToDestroy: 2,
  extraLifeScoreInterval: 20000,
  playerFirepower: {
    1: { bulletSpeed: 225, maxBullets: 1, destroysSteel: false },
    2: { bulletSpeed: 270, maxBullets: 1, destroysSteel: false },
    3: { bulletSpeed: 270, maxBullets: 2, destroysSteel: false },
    4: { bulletSpeed: 300, maxBullets: 3, destroysSteel: true },
  },
  enemyTypes: {
    normal: { movementSpeed: 50, bulletSpeed: 225, fireCooldownMs: 1250, health: 1, score: 100 },
    fast: { movementSpeed: 70, bulletSpeed: 270, fireCooldownMs: 1050, health: 1, score: 200 },
    power: { movementSpeed: 58, bulletSpeed: 300, fireCooldownMs: 850, health: 1, score: 300 },
    armor: { movementSpeed: 58, bulletSpeed: 270, fireCooldownMs: 1050, health: 4, score: 400 },
  },
  bulletSpeed: 225,
  maxPlayerPowerLevel: 4,
  powerUpScore: 500,
  powerUpSpawnIntervalMs: 8500,
  powerUpDurations: {
    helmetMs: 8000,
    shovelMs: 10000,
    clockMs: 6500,
  },
} as const;

export const GAME_WIDTH = CONFIG.gridColumns * CONFIG.tileSize + CONFIG.sidePanelWidth;
export const GAME_HEIGHT = CONFIG.gridRows * CONFIG.tileSize;
